using csStorage.Base.csEntityBaseModel;
using csStorage.Exceptions;
using csStorage.Shared;
using System.Collections.Immutable;

namespace csStorage.Builder.csContextBuilder;

public partial class csContextBuilder<T>
{    private void SetEntity(csEntityBaseModel<T> entity)
    {
        entity.csKey = this.csKey;
        this.Entity = entity;
    }

    private void SetCsKey(csEntityBaseModel<T> entity)
    {        
        foreach (var propertyInfo in entity.GetType().GetProperties())
        {
            foreach (var obj in propertyInfo.GetCustomAttributes(true))
            {
                if (obj is csKey)
                {
                    var propertyValue = propertyInfo?.GetValue(entity)?.ToString();
                    if (!string.IsNullOrEmpty(propertyValue))
                    {
                        this.csKey = propertyValue;
                    }
                }
                if (obj is csAutoKey)
                {
                    var propertyType = propertyInfo?.PropertyType;

                    if (propertyType != typeof(int) && propertyType != typeof(Guid))
                    {
                        throw new CsAutoKeyNeedToBeIntOrGuidTypeException();
                    }
                    var propertyValue = propertyInfo?.GetValue(entity);

                    if ((propertyValue!.GetType() == typeof(int) && (int)propertyValue == 0) ||
                        ((propertyValue!.GetType() == typeof(Guid) && (Guid)propertyValue! == Guid.Empty))    
                    )
                    {
                        this.SetCsAutoKeyProperties(nameof(csAutoKey), propertyType);
                    }
                    else
                    {                        
                        this.SetCsAutoKeyProperties(propertyValue.ToString()!, propertyType);                        
                    }
                }
            }
        }        

        if (string.IsNullOrEmpty(this.csKey))
        {
            throw new CsKeyAttributeHasNotBeenSetException();
        }
    }

    private void SetCsKeyWithAutoGeneratedValue(IEnumerable<T> allRecords, csEntityBaseModel<T> entity)
    {
        if (this.AutoKeyType == typeof(int))
        {
            var entityBaseModelList = this.ConvertGenericListToEntityBaseModelList(allRecords);
            int firstAvailableKey;

            if (entityBaseModelList.Count > 0)
            {
                var sortedListOfKeys = entityBaseModelList
                    .Select(x => Convert.ToInt32(x.csKey))
                    .ToImmutableSortedSet();

                firstAvailableKey = this.FindFirstAvailableKey(sortedListOfKeys);
            }
            else
            {
                firstAvailableKey = 0;
            }

            this.csKey = (firstAvailableKey + 1).ToString();
        }

        if (this.AutoKeyType == typeof(Guid))
        {
            this.csKey = Guid.NewGuid().ToString();
        }

        this.SetEntity(entity);
    }

    private void SetDirectoryPath()
    {
        this.DirectoryPath = AppDomain.CurrentDomain.BaseDirectory + $"\\csStorage";

        if (!Directory.Exists(this.DirectoryPath))
        {
            Directory.CreateDirectory(this.DirectoryPath);
        }
    }

    private void SetStoragePath()
    {
        this.StoragePath = this.DirectoryPath + $"\\{typeof(T).Name}.csv";
    }

    private void SetContextBuilderProperties(csEntityBaseModel<T>? entity)
    {
        this.IsEntityValid(entity);
        this.SetCsKey(entity!);
        this.SetEntity(entity!);
    }

    private void SetSuccessResult()
    {
        this.Result = ResultStatus.Success;
    }

    private void SetCsAutoKeyProperties(string propertyValue, Type propertyType)
    {
        this.IsAutoKey = true;
        this.AutoKeyType = propertyType;
        this.csKey = propertyValue;
    }
}
    